Update 16-status-check.yaml

diff --git a/.github/workflows/16-status-check.yaml b/.github/workflows/16-status-check.yaml
--- a/.github/workflows/16-status-check.yaml
+++ b/.github/workflows/16-status-check.yaml
@@ -11,8 +11,12 @@ jobs:
             - name: Step 1
               run: sleep 20
 
-            - name: FailStep
-              run: exit 1     
+            - name: Step 11
+              run: exit 1  
+              
+            - name: Runs on Step 11 Failure
+              if: steps.step-11.conclusion == 'failure' # se ejecuta solo si el paso 11 falla
+              run: echo "This job runs only on step 11 failure"
 
             - name: Runs on Failure
               if: failure() # failure() es una función que devuelve true si el job falla
